{% set version = "0.8.13" %}

package:
  name: hdbscan
  version: {{ version }}

source:
  fn: hdbscan-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/h/hdbscan/hdbscan-{{ version }}.tar.gz
  sha256: 31874db29375816688b5541287a051c9bd768f2499ccf1f6a4d88d266530e2a6

build:
  number: 0
  script: 
    - source activate "${CONDA_DEFAULT_ENV}"  # [unix]
    - python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - toolchain
    - python
    - setuptools
    - scikit-learn >=0.16
    - cython >=0.17
    # 1.9 is the earliest for scikit-learn 0.16
    - numpy 1.9.*  # [not (win and (py35 or py36))]
    - numpy 1.9.*  # [win and py35]
    - numpy 1.11.*  # [win and py36]

  run:
    - python
    - scikit-learn >=0.16
    - numpy >=1.9  # [not (win and (py35 or py36))]
    - numpy >=1.9  # [win and py35]
    - numpy >=1.11  # [win and py36]

test:
  imports:
    - hdbscan

about:
  home: http://github.com/lmcinnes/hdbscan
  license: BSD 3-Clause
  summary: 'Clustering based on density with variable density clusters'

extra:
  recipe-maintainers:
    - lmcinnes
