{% set version = "0.8.33" %}
{% set name = "hdbscan" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 57fabc5f0e45f48d2407b35c731192abc896376411fe7e4bb836ffa03d38f90d
build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython 0.29.36
    - numpy {{ numpy }}
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - scikit-learn >=0.20
    - joblib >=1.0
    - numpy >=1.20
    - scipy >=1.0

test:
  requires:
    - pip
    # cython only required for pip check.
    - cython >=0.27,<3
  imports:
    - hdbscan
  commands:
    - pip check

about:
  home: https://github.com/scikit-learn-contrib/hdbscan
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Clustering based on density with variable density clusters
  description: |
    HDBSCAN - Hierarchical Density-Based Spatial Clustering of Applications with Noise. 
    Performs DBSCAN over varying epsilon values and integrates the result to find a clustering 
    that gives the best stability over epsilon. This allows HDBSCAN to find clusters of varying 
    densities (unlike DBSCAN), and be more robust to parameter selection. 

    In practice this means that HDBSCAN returns a good clustering straight away with little or 
    no parameter tuning -- and the primary parameter, minimum cluster size, is intuitive and 
    easy to select.

    HDBSCAN is ideal for exploratory data analysis; it's a fast and robust algorithm that you 
    can trust to return meaningful clusters (if there are any).
  doc_url: https://hdbscan.readthedocs.io/en/latest/how_hdbscan_works.html
  dev_url: https://github.com/scikit-learn-contrib/hdbscan

extra:
  recipe-maintainers:
    - johnlees
    - lmcinnes
