{% set version = "0.8.8" %}

package:
  name: hdbscan
  version: {{ version }}

source:
  fn: hdbscan-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/h/hdbscan/hdbscan-{{ version }}.tar.gz
  sha256: 15838bc7eb75d35770d2cd5a926fa6ef2d58527db5cb66e7d172aa167ad2faf9

build:
  number: 0
  script: 
    # FIXME: This is a hack to make sure the environment is activated.
    # The reason this is required is due to the conda-build issue
    # mentioned below.
    #
    # https://github.com/conda/conda-build/issues/910
    #
    - source activate "${CONDA_DEFAULT_ENV}"  # [unix]
    - python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - toolchain
    - python
    - setuptools
    - scikit-learn >=0.16
    - cython >=0.17

  run:
    - python
    - scikit-learn >=0.16

test:
  imports:
    - hdbscan

about:
  home: http://github.com/lmcinnes/hdbscan
  license: BSD 3-Clause
  summary: 'Clustering based on density with variable density clusters'

extra:
  recipe-maintainers:
    - lmcinnes
