travis:
  secure:
    BINSTAR_TOKEN: mU4Mft03py/D+UVyRKXuIeXbQXnz80WESRDOJygt7uxbQaZKMO6hPrC9q0Ao9tXX+/12zypAe7CJqt84ydg/HMM7inS6HvtvORi8wosO3Y+/fMXMO4oYe6FmFEcy8gP0bzGid5B90vjz06Yg0kTT9Kb+FpI1Px2wt/x0IJuZzpakyYfZTHiyB/6V36R1d5ZD29ST2IeYRvMOHTWLGu7AbnPOrTEVU76kNoI+eh3Lh/uY0LmVFmUXF20F3drd9Rr5OBm6KTuLmuOc1D621INbkczinZ43rO5GShttKyoaFZHu9DOmmX98nhc7/wWtgBe0TvaEYwHBG0lNiQ42cLcaRCQW8M/FOYlfKgtvFlT2TvpcCu6yAqeM+76NqTpt+EiMXB2aLPK2xLPi3RbbXaD8FX5FNcUF8ihXa1P5RCk/jWm9q4fOtp55/Gey4DmvkQ5gk1g2uttCuZmNSChsaA1BIEKDTvHnOfwjwo4JnboSXpY/H/cYXagAulrT2ob4QGXwL9JlHMZuv4Wh/g+O3DW8lIFW7rPMuhzWulplyO+f2BBNvbTZmw7lA/DFWytnWSBZw6U4mPD7Vl+YD6KFVghOEmQO2G08wQh63r+/zBdVO5p3JbrKccnhCDDeohmspQ3qtSHoaON1q5Qck6gmSWsUDTUc19dYt1hFwYqCRlUoZkE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
