travis:
  secure:
    BINSTAR_TOKEN: tguWFG2exZf6A0714i2dA9u7mv5lM8LPsr+ReGR3Nf6MYd5fEAZnfPont0tPBbwGjX3Z3X6iwhg7SDp8PycJg9Hxj9zXIFvveH9VMA73mErEh27QRSwiE/RWfTCalWWUCnf6R5rcUL/heZL1obNMI3DNz/SVrPkjoJAYCtrnG5Bpr1RgKQce8ofiLKNQOm08eFYIQk11/5RqqmRIVgLvKUIcoph8whAio+prBzzEVOtOETvKB9mBvSdnfQVtboiKKqpErUPIR97tf4p0doXlLUeE4gBgqa76gTkgOaSZlVFLh/uTOd39iPdrG7eVpHKUh+SSGy2JHbE7rEE/XIoxgzqd+riRGOyrO5wTbyZ3xMUMFyyuPU1z+BhCTbT+nf7SRP1YrXfqt890iZMNLvblSWJRA0UajZSi1euJCzo9z6VPmMqZq5/VKprqPcbs9j8KgKYpdPlkdKqE6I2CT1lH8J/bFW1jL5+7UU67C26MaQDGmMPlJ0RJX3IQRezlRSH0LONE67DFOATahcGUtOet1KlgcpxhLu7pR/t3iseBRPKiVgS6PL1PuLoRcH/hV+wqPpyyv91ohajO5vl33KHKZvppVTLsaoMBYsul/oZRjOqkQb8uuguVnTKr485acRJIkLa75YlbRQRmyMm9r7mD1l21eHn054zuXYfiA1m5b90=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
