travis:
  secure:
    BINSTAR_TOKEN: lXnf71H+Qz4mvsWaS9ohPMAU8WAs9RaCMlV8YCjNEXsSUgQgDo/mn9Z4aPQjGrXoirxFSxiEODTUhCO/zPo54nCnLq5uLW8NbmB9K+bbiFEgs+No09fRhj9dWuhK3t+nerNTIUn29lDbpyMJS/QS5vHUV1VpxmjJoi+MItrXVa5hOaBomMzwL88KL5walWeDo6SWh1JlwIHjX83mqVoTfIkSYh/DDIN94z0ug4WM7abptYSDD2MpGSXW4kVnvJfmm+Zf721wGdxOmxy2N//RaaFbyzXX8as1u4fZ0QMiSWmP5TvWCnVPXns8YnOfIiJlpAuNXdnqdsWPQeWsumLpjp22OLhWZvM7X8RlfEyJvW4aR3SF5ckEMpIaMYlcNuizkmp9b3QNVt6WQKhk2kxjmzA/722XhCM1I/Xb49Ta+HEKjUrBPEIZaXb552u+GzIf+XI0YuUAvqBz/lTX4eWVfTTbbFMDBBT6rTBoNqVl7nTN9ykj5HCDfH7nMXPUz2YWfG77pMWAIzpP2v/n8JGhrUstDE6xhqaaTVRUxdSC5CT5GsQEgLMzlqfc1tE73enAiCDchrtJvEHmBdqVCrO47id7CT0tNwJ+lEZo8f1MdPzfXUuB70Ex6UdE7E7at7cvCr9sgv2dCp9hHWeb+NYFuOHACoC8nypJ4gxz/8ccNws=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
