travis:
  secure:
    BINSTAR_TOKEN: CjpkIjwXdMiLDY7tttZ17vCuUpMwOMpHBdKQBSJIw9mN5FsZLqH0I3K4fHwu2U0Kq/OGYL+Ew3VV8gKG82T+69Vw7b9shTtzTQnt+2AV4UM5LXFLucgEAxmaSrrYHBFW9MHd0chlj9ATON8wwieegnIMeGbwVKTXRpsa+Bo5AWqPlTzbDaktnPlAPwekPhSKsFMcs032eTf+47zS3T42glZr49X+0TzBj1H3NH93ARN3dMXLnJkH/06IYNkbCpOiXIqdyv+tMFrENt8dXzj+OdcYhWd8oMrG/dTar661AXU43hyJbC17WToERnPhX3+x6l3nO16Aerhge4C9yMeNyEhq+f0KZnx7z/5YzcspmDUYSgcMK63PZ5BJ6Ok33hkNhAMLJcdOikqSCrXMJenBt5Csw9MsKpWABUeKjE0J4L3iKAV3TLto47pmmARlEwHOBAELqmF5XxIN6ODazVSPbHspzaiejkQ98OzmX+jQ1PF9Z+OyjZClAANcpTBYJ/hA5sPNzc3oKyX4ITgGB7Oq7mGvK7aOhIC81fgUfqDwkT5jb7xRmaENFKc/MZjpWuGokerRzFdyKYu9h807MZGuYVjPUitmPt+y58aNDE/OCkS50/m4WAtobqlwLWys0yl/PlriErj/29KxgTZqI4XR3hVQvaDKTjv1ps4Et1HtTn8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
