travis:
  secure:
    BINSTAR_TOKEN: bFSOcHdiUVOi5pdPIej+gQ4Dy9IbmbDjshVOKRFHY3hoDPkfU8JDLFd8jZJwisvMEui074Y6NOUtLFDNVGZ8Evh4ilSd007LLnILqnWjfORC3C/JLs28/QoOKCIZ80rR+zVp4iB/RM3lI5haqMNxk0KNukLEtDH2YfGYtwQ3szG8yHJNwONy7c6d071p26hLFcDuiDJFGO5ByW4Mepyv5SGf4lfBYNNa2NU3+wlsTKa1nnVb3cu6o+7yyBDeC9dg1XLnzv/lpOsrOwe5ZSC679bOOzr3VYgMUwEDWELGyKG3LlZkRVFJNuOXGv2kkspErDaOAgRfFk43hcpdrtvYzr1vH//KZL6iODZl/TrYXGtYKm0/FgqeUyfjYIbyqi3ERao6ZTUST2paarK86C4xWGoYMqZJxwhZ8h+bFaetTihkm6Bw19kjBHHdWnda0GZGaycLnaxhmBRFEe7zygGjsdBbfYV3+us3xRNwdVQe3LE4NiautFGzRxPgx8Wm9OPXLwwJBMFv3xynCb1CkhIyx+N95DKx0w9qSiV4x2I3gnN9rysh9zXvK7xJ52dw1UFyfTQy/hP9qG/PlW7/Z6fLG/WYc8rKYRZEevIIjt+FKJPkR7NE9GDME7/FH8hVk8GAhlOKldzvMa3qfDwRPdFubYBw5jsRGRz0a5CntMMJsLk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
