travis:
  secure:
    BINSTAR_TOKEN: rB4OWoybiOR7PXoZO1G45ZyGwKvvkE8Mh5dOaD2bpZ9p9UjAGsFzrKbWUDdG4KLhkFxmkBCfixc44IlVwlx4l4+VRJha9TxBZYm+SUPuAeh/L00Fcbn4cEUhWjmqJwLpOZI0j0CaQ+Rh8UISHOkKZ3e9Wvq+JPRaBBlX7vGR3c49L6XJUFDODFnAXkL9fBvIW/z4QR+aBMrY2iuz0cxHg7d8D9Cyvow7XQzXs7ccx4AjeKwvZm02BFMxz5uusHdBbbVKWxCnGv1VoNC7HwOPzXq+JhAaLB5sgsDT53BH8Ccmp16k1/46YxbbPF0OFhKydgBhq1/+ZiyJ8/lqNBKIikTVXK5+NmGiVMmq49ihbQAf/KvNpyKxK3xwtrOC/KbvsJUn53rcNv86OouZgONPPJQhmne/4cz7KNIHh1mv7lNnRSUKhS2wpKkQwN3KnAAiolOdHsmgyLTPi3JCqw3hqxKs4dMH/5lw9AoKiHnNLXYPZrdnJtq8RCSyJOtF/hYhLzlJAf+UGsCVh2SY8xwjp2KHDgBwSj7oWAWa02m+PWtR9Uj3tu+KPvWvROrawOQmY1BBeQsVUjPFieZSCvkMVliig0IgvjRa5qP/xiPSIEi0nls/2wkNO4AKIpcduCG5oOFjTgWd3MOV3UpWwLefCtQkcGox8e8AGDdA0iGcflo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
