travis:
  secure:
    BINSTAR_TOKEN: QONjNdHNIcczbC/7IXvHP30n8s+V8Iqf184u2KUb2lxxbopBjH+vd7LJPTZ+AVkPAJ8QKTOmHVrwTylMBts4BJgt6HE4BXuj0OgDjM6dAJmgwC7xE9kMHuxxDLrb1+iDm7YLMTWod3GhXyonAiZadlF1NOX10OzJrn8zTva/P+MgM5uPhd/qArFMQREE+l3FW6Zmwr60rKWUt2UxDrcmlBt9ZRM7ZMZOshQZioaG+16rOkdUxAT1VOnfOhJz/aUzJxr1BeZTuBV6Gm+QgOPCG07VN52Z9Aw9c86TteJIYhREuauqBtRb9dUVmu4h37Skal8ejdujOk2M61r5MizToqL7RcpUfKPXyqNNmsAAJHnB8wG0RKv4T8qPpTwXgtGVl/yLFPnJq4dLw4HpD02F8jCAQc0dVvsgtziAhN80Xje4UBhoxDbYM17GF1jen6IiKzwX9bGe1p0CXEXk6I2Gdy72h6787MFZbRqzDO5krYSa4g0Eb+AtVSdWGDCnAGVY+vAvBzMLr5fSbdmYbCVW/aLjj8mn/0GC0QhQpc9RYYt1NBlVsHjjCWUGppppxNpdQzjbAS335+08IUxstjXPuWjxu2TylgRGOyvEHHyJWE3dJHCeioZ5mMZ2y3ZDJun4IJFk0wk1S6SFNjV8gmRA3nwGnASD1AtgZj65b5YXvx4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
