appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: d8EX1Z1Qd6NdTetvyCTlbc3d2RadRK5lG6PKOwjyC/qT6RQLFHLKj/kYBRjp+lspE7HK5/nWvElGbJCRxg40vDN604lq8cHN412ZQeQZBChSBDtwFtVgin0iwFutnnfS3WWN9h8id6ez0AbzvbpKynbmhmwoKa4oD/R1L4ojHWKLK7qmaPeuO7HZv/UC4AmVE+Wt/0tNt5jSoWF8kzF3VIiNZl7xzycBqxDusOr35SBvX+XWomAqW3BlwAAR3/hxWreMHEJxoOEQPOfj1ulKuG/zbivTTUWqyKbrcfI4ca3BbeZc+mRKjIDCl/P23RRkYgiDSbaNoZzoXXQHiQGKbzmRdM+IrH8wYpw4FKzT9qckqL/xap+6YcDw7ffUzh01ETvbs3MZ8maDVCOmPZ1KLFRKzaKaUyqAr/6UkW6Q77R5tBotDMOxIHXcWtg64AdHfWm1r/2d0Gqtz8PQ1oY9hmgReELtaUrgHrgONctztoBQCQfucC0v52gMkeZGPLFgvIEWXdmpJGHyn/rPga8SMP0fCqrwAeqEcVt/uJPfrW6AOufpjVtvNHLzQcCLwodNswqfUKvrEEJA6XylfFCax8rcilta3ZAn0VIo5hlJoOtvhdcVUnJv39eZRqSCdfqCX7jRabEMugg8il+EdFFKPqzqmZ483QoLiSJDFt4ZqhM=}
provider:
  win: azure
